import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Search, ShoppingBag, Plus, Utensils, ChevronLeft, AlertCircle } from "lucide-react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { getPublicMenuByTableCode } from "../../api/menu";
import { useCart } from "../../context/CartContext";
import Spinner from "../../components/ui/Spinner";

const fallback={primary_color:'#B8793E',secondary_color:'#5B7A52',text_color:'#171717',button_color:'#171717',card_style:'rounded',show_menupilot_branding:true};
export default function Menu(){
 const {tableCode}=useParams(),navigate=useNavigate(),[searchParams]=useSearchParams(),sessionId=searchParams.get('session');
 const {addItem,items}=useCart(); const [menuItems,setMenuItems]=useState([]),[restaurant,setRestaurant]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[query,setQuery]=useState(''),[activeCategory,setActiveCategory]=useState('الكل'),[addedItem,setAddedItem]=useState('');
 useEffect(()=>{let cancelled=false;getPublicMenuByTableCode(tableCode).then(result=>{if(!cancelled){setMenuItems(result.items||[]);setRestaurant(result.restaurant||result.table||null)}}).catch(err=>{if(!cancelled)setError(err)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[tableCode]);
 const branding={...fallback,...(restaurant?.branding||{})}; const categories=useMemo(()=>['الكل',...new Set(menuItems.map(i=>i.category).filter(Boolean))],[menuItems]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return menuItems.filter(i=>(activeCategory==='الكل'||i.category===activeCategory)&&(!q||`${i.name} ${i.description||''}`.toLowerCase().includes(q)))},[menuItems,query,activeCategory]);
 const cartCount=items.reduce((s,i)=>s+(i.quantity||1),0),cartPath=`/t/${tableCode}/cart${sessionId?`?session=${encodeURIComponent(sessionId)}`:''}`;
 if(loading)return <Spinner label="جارِ تجهيز قائمتك…"/>;
 if(error)return <div dir="rtl" className="grid min-h-screen place-items-center bg-paper-2 px-6 text-center text-ink"><div className="w-full max-w-sm rounded-[28px] border border-brick/15 bg-paper p-8 shadow-xl"><AlertCircle className="mx-auto text-brick"/><h1 className="mt-5 text-2xl font-bold">تعذّر تحميل القائمة</h1><p className="mt-2 text-sm leading-7 text-ink-soft">{error.message||'حدث خطأ غير متوقع.'}</p><button onClick={()=>window.location.reload()} className="mt-6 w-full rounded-2xl bg-ink px-5 py-3 text-sm font-bold text-paper">حاول مرة أخرى</button></div></div>;
 const restaurantName=restaurant?.name||restaurant?.restaurant_name||'مطعمك المفضل'; const radius=branding.card_style==='square'?'8px':branding.card_style==='soft'?'20px':'28px';
 return <div dir="rtl" className="min-h-screen bg-paper-2 pb-32" style={{color:branding.text_color,fontFamily:branding.font_family&&branding.font_family!=='system'?branding.font_family:undefined}}>
  <header className="relative overflow-hidden text-paper" style={{backgroundColor:branding.primary_color,backgroundImage:branding.background_url?`linear-gradient(#0005,#0005),url(${branding.background_url})`:undefined,backgroundSize:'cover',backgroundPosition:'center'}}><div className="mx-auto max-w-5xl px-5 pb-8 pt-6 sm:px-8"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>navigate(-1)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/20 bg-white/10"><ArrowRight size={19}/></button><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/90 text-ink">{branding.logo_url?<img src={branding.logo_url} className="h-full w-full object-cover"/>:<Utensils size={20}/>}</div><div className="min-w-0"><p className="truncate text-base font-black">{restaurantName}</p><p className="text-xs text-white/70">طاولة {tableCode}</p></div></div><button onClick={()=>navigate(cartPath)} className="relative grid h-11 w-11 place-items-center rounded-2xl border border-white/20 bg-white/10"><ShoppingBag size={20}/>{cartCount>0&&<span className="absolute -left-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full px-1 text-[10px] font-black" style={{background:branding.secondary_color}}>{cartCount}</span>}</button></div><div className="mt-8"><p className="text-sm font-medium" style={{color:branding.secondary_color}}>أهلاً بك 👋</p><h1 className="mt-1 text-4xl font-black leading-tight sm:text-5xl">ماذا ترغب اليوم؟</h1><p className="mt-2 text-sm leading-6 text-white/70">تصفح القائمة واختر طلبك.</p></div><label className="mt-6 flex items-center gap-3 rounded-2xl bg-white px-4 py-3 text-ink shadow-xl"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن طبق…" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label></div></header>
  {addedItem&&<div className="fixed inset-x-4 top-4 z-50 mx-auto flex max-w-sm items-center justify-center gap-2 rounded-2xl bg-herb px-4 py-3 text-sm font-bold text-paper"><Check size={17}/>تمت إضافة الطبق إلى السلة</div>}
  <main className="mx-auto max-w-5xl px-5 sm:px-8"><div className="flex gap-2 overflow-x-auto py-5">{categories.map(c=><button key={c} onClick={()=>setActiveCategory(c)} className="whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold" style={activeCategory===c?{background:branding.button_color,color:'#fff'}:{background:'#fff',border:'1px solid #0002'}}>{c}</button>)}</div><div className="mb-5 flex items-end justify-between"><div><p className="text-xs opacity-60">اكتشف قائمتنا</p><h2 className="mt-1 text-2xl font-bold">الأطباق المتاحة</h2></div><span className="text-xs opacity-55">{filtered.length} طبق</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item=><article key={item.id} className="overflow-hidden border border-black/10 bg-white shadow-sm" style={{borderRadius:radius}}><div className="relative aspect-[4/3] overflow-hidden bg-black/5">{item.imageUrl?<img src={item.imageUrl} alt={item.name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center"><Utensils style={{color:branding.primary_color}} size={42}/></div>}</div><div className="p-5"><h3 className="text-xl font-bold">{item.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 opacity-65">{item.description||'طبق محضر بعناية.'}</p><div className="mt-5 flex items-center justify-between gap-3"><span className="text-lg font-black" style={{color:branding.primary_color}}>{item.price} ₪</span><button onClick={()=>{addItem(item);setAddedItem(item.id)}} className="flex items-center gap-2 rounded-2xl px-4 py-2.5 text-sm font-bold text-white" style={{background:branding.button_color}}><Plus size={17}/>إضافة</button></div></div></article>)}</div></main>
  {cartCount>0&&<div className="fixed inset-x-4 bottom-4 z-40 mx-auto max-w-5xl"><button onClick={()=>navigate(cartPath)} className="flex w-full items-center justify-between rounded-2xl bg-ink px-5 py-4 text-paper shadow-2xl"><span className="flex items-center gap-3"><ShoppingBag size={19}/><span className="text-right"><b className="block text-sm">عرض طلبك</b><span className="text-xs text-paper/50">{cartCount} عناصر في السلة</span></span></span><span className="flex items-center gap-1 rounded-xl px-4 py-2.5 text-sm font-black text-white" style={{background:branding.button_color}}>السلة <ChevronLeft size={17}/></span></button></div>}
  {branding.show_menupilot_branding&&<p className="mt-8 text-center text-[11px] opacity-40">Powered by menuPilot</p>}
 </div>
}
