<?php
namespace App\Http\Controllers;
use App\Http\Requests\LoginRequest; use App\Http\Requests\RegisterRequest; use App\Models\Owner; use App\Models\Restaurant; use Carbon\Carbon; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str;
class AuthController extends Controller {
 public function register(RegisterRequest $r){$v=$r->validated();$result=DB::transaction(function()use($v){$restaurant=Restaurant::create(['name'=>$v['restaurant_name']]);$owner=Owner::create(['restaurant_id'=>$restaurant->id,'name'=>$v['name']??$v['restaurant_name'],'email'=>$v['email'],'password'=>$v['password'],'phone'=>$v['phone']??null,'plan'=>$v['plan']??'basic','role'=>'owner','active'=>true]);return ['owner'=>$owner,'restaurant'=>$restaurant];});$token=$result['owner']->createToken('auth_token',["tenant_id:{$result['restaurant']->id}"])->plainTextToken;return response()->json(['message'=>'تم إنشاء الحساب بنجاح','token'=>$token,'access_token'=>$token,'user'=>['id'=>$result['owner']->id,'email'=>$result['owner']->email,'name'=>$result['owner']->name,'role'=>'owner','restaurantName'=>$result['restaurant']->name]],201);}
 public function login(LoginRequest $r){$c=$r->validated();$o=Owner::where('email',$c['email'])->where('active',true)->first();if(!$o)return response()->json(['message'=>'بيانات الدخول غير صحيحة'],401);if($o->locked_until&&Carbon::now()->isBefore($o->locked_until))return response()->json(['message'=>'الحساب مغلق مؤقتاً. حاول مجدداً لاحقاً.'],423);if(!Hash::check($c['password'],$o->password)){ $o->increment('failed_attempts');if($o->failed_attempts>=5){$o->update(['locked_until'=>Carbon::now()->addMinutes(15),'failed_attempts'=>0]);return response()->json(['message'=>'تم قفل الحساب لمدة 15 دقيقة بسبب كثرة المحاولات الخاطئة.'],423);}return response()->json(['message'=>'بيانات الدخول غير صحيحة'],401);} $o->update(['failed_attempts'=>0,'locked_until'=>null]);$token=$o->createToken('auth_token',["tenant_id:{$o->restaurant_id}"])->plainTextToken;return response()->json(['message'=>'تم تسجيل الدخول بنجاح','token'=>$token,'access_token'=>$token,'token_type'=>'Bearer','user'=>['id'=>$o->id,'email'=>$o->email,'name'=>$o->name,'role'=>$o->role,'restaurantName'=>$o->restaurant?->name,'plan'=>$o->plan]]);}
 public function me(Request $r){$o=$r->user()->load('restaurant');return response()->json(['id'=>$o->id,'email'=>$o->email,'name'=>$o->name,'role'=>$o->role,'restaurantName'=>$o->restaurant?->name,'restaurant'=>$o->restaurant,'plan'=>$o->plan??'basic']);}
 public function logout(Request $r){$t=$r->user()->currentAccessToken();if($t)$t->delete();return response()->json(['message'=>'تم تسجيل الخروج وإبطال التوكن بنجاح']);}
 public function forgotPassword(Request $r){$d=$r->validate(['email'=>'required|email']);$o=Owner::where('email',$d['email'])->first();$token=Str::random(64);if($o)DB::table('password_reset_tokens')->updateOrInsert(['email'=>$o->email],['token'=>Hash::make($token),'created_at'=>now()]);return response()->json(['message'=>'تم تجهيز إعادة تعيين كلمة المرور','token'=>$o?$token:null]);}
 public function resetPassword(Request $r){$d=$r->validate(['token'=>'required|string','email'=>'required|email','password'=>'required|string|min:8|confirmed']);$row=DB::table('password_reset_tokens')->where('email',$d['email'])->first();if(!$row||!Hash::check($d['token'],$row->token))return response()->json(['message'=>'رمز إعادة التعيين غير صحيح'],422);$o=Owner::where('email',$d['email'])->firstOrFail();$o->update(['password'=>$d['password']]);DB::table('password_reset_tokens')->where('email',$d['email'])->delete();return response()->json(['message'=>'تم تغيير كلمة المرور بنجاح']);}
}
