<?php
namespace App\Http\Controllers;
use App\Http\Requests\LoginRequest; use App\Http\Requests\RegisterRequest; use App\Models\Owner; use App\Models\Restaurant; use Carbon\Carbon; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash;
class AuthController extends Controller {
 public function register(RegisterRequest $r){$v=$r->validated();$result=DB::transaction(function()use($v){$restaurant=Restaurant::create(['name'=>$v['restaurant_name']]);$owner=Owner::create(['restaurant_id'=>$restaurant->id,'name'=>$v['name'],'email'=>$v['email'],'password'=>$v['password'],'phone'=>$v['phone']??null]);return ['owner'=>$owner,'restaurant'=>$restaurant];});return response()->json(['message'=>'تم إنشاء حساب المالك والمطعم بنجاح','data'=>$result],201);}
 public function login(LoginRequest $r){$c=$r->validated();$o=Owner::where('email',$c['email'])->first();if(!$o)return response()->json(['message'=>'بيانات الدخول غير صحيحة'],401);if($o->locked_until&&Carbon::now()->isBefore($o->locked_until))return response()->json(['message'=>'الحساب مغلق مؤقتاً. حاول مجدداً لاحقاً.'],423);if(!Hash::check($c['password'],$o->password)){ $o->increment('failed_attempts'); if($o->failed_attempts>=5){$o->update(['locked_until'=>Carbon::now()->addMinutes(15),'failed_attempts'=>0]);return response()->json(['message'=>'تم قفل الحساب لمدة 15 دقيقة بسبب كثرة المحاولات الخاطئة.'],423);}return response()->json(['message'=>'بيانات الدخول غير صحيحة'],401);} $o->update(['failed_attempts'=>0,'locked_until'=>null]);$token=$o->createToken('auth_token',["tenant_id:{$o->restaurant_id}"])->plainTextToken;return response()->json(['message'=>'تم تسجيل الدخول بنجاح','token'=>$token,'access_token'=>$token,'token_type'=>'Bearer','owner'=>$o->load('restaurant')]);}
 public function me(Request $r){$o=$r->user()->load('restaurant');return response()->json(['id'=>$o->id,'email'=>$o->email,'name'=>$o->name,'role'=>'owner','restaurantName'=>$o->restaurant?->name,'restaurant'=>$o->restaurant]);}
 public function logout(Request $r){$t=$r->user()->currentAccessToken();if($t)$t->delete();return response()->json(['message'=>'تم تسجيل الخروج وإبطال التوكن بنجاح']);}
}
