<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class BillingController extends Controller{
 private function out($d,$s=200){return response()->json(['data'=>$d],$s);}private function total($sid){$x=DB::table('order_items')->join('orders','orders.id','=','order_items.order_id')->where('orders.dining_session_id',$sid)->where('order_items.status','active')->select(DB::raw('SUM(order_items.quantity*order_items.unit_price) total'))->first();return $x->total??0;}
 public function request($sid){if(!DB::table('dining_sessions')->find($sid))return response()->json(['message'=>'Session not found'],404);DB::table('dining_sessions')->where('id',$sid)->update(['status'=>'bill_requested','updated_at'=>now()]);return $this->out(['message'=>'Bill requested']);}
 public function bill($sid){$items=DB::table('order_items')->join('orders','orders.id','=','order_items.order_id')->join('menu_items','menu_items.id','=','order_items.menu_item_id')->where('orders.dining_session_id',$sid)->where('order_items.status','active')->select('order_items.id','menu_items.name','order_items.quantity','order_items.unit_price',DB::raw('(order_items.quantity*order_items.unit_price) as total'))->get();return $this->out(['items'=>$items,'total'=>$items->sum('total')]);}
 public function pay(Request $r,$sid){$v=$r->validate(['method'=>'required|in:cash,electronic,ussd']);$s=DB::table('dining_sessions')->find($sid);if(!$s)return response()->json(['message'=>'Session not found'],404);$amount=$this->total($sid);$id=DB::table('payments')->insertGetId(['dining_session_id'=>$sid,'method'=>$v['method'],'amount'=>$amount,'paid_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);DB::table('dining_sessions')->where('id',$sid)->update(['status'=>'closed','closed_at'=>now(),'updated_at'=>now()]);DB::table('restaurant_tables')->where('id',$s->restaurant_table_id)->update(['status'=>'available','updated_at'=>now()]);return $this->out(DB::table('payments')->find($id),201);}
 public function adjust(Request $r,$sid,$item){$v=$r->validate(['new_price'=>'required|numeric|min:0']);$x=DB::table('order_items')->join('orders','orders.id','=','order_items.order_id')->where('order_items.id',$item)->where('orders.dining_session_id',$sid)->select('order_items.*')->first();if(!$x)return response()->json(['message'=>'Bill item not found'],404);DB::table('bill_adjustments')->insert(['dining_session_id'=>$sid,'order_item_id'=>$item,'old_price'=>$x->unit_price,'new_price'=>$v['new_price'],'cashier_id'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);DB::table('order_items')->where('id',$item)->update(['unit_price'=>$v['new_price'],'updated_at'=>now()]);return $this->out(DB::table('order_items')->find($item));}
}
