<?php
namespace App\Http\Controllers;
use App\Models\Product; use App\Models\Table; use App\Models\Category; use Illuminate\Http\Request;
class MenuController extends Controller {
 public function index(Request $r){return response()->json(['data'=>Product::with('category')->where('restaurant_id',$r->user()->restaurant_id)->orderBy('category_id')->orderBy('name')->get()]);}
 public function store(Request $r){$d=$r->validate(['name'=>'required|string|max:255','price'=>'required|numeric|min:0','category_id'=>'nullable|integer','category'=>'nullable|string|max:100','imageUrl'=>'nullable|string|max:2048','image'=>'nullable|string|max:2048','active'=>'nullable|boolean','is_available'=>'nullable|boolean']);$categoryId=$d['category_id']??null;if(!$categoryId&&isset($d['category'])){$c=Category::firstOrCreate(['restaurant_id'=>$r->user()->restaurant_id,'name'=>$d['category']],['display_order'=>0]);$categoryId=$c->id;}$p=Product::create(['restaurant_id'=>$r->user()->restaurant_id,'category_id'=>$categoryId,'name'=>$d['name'],'price'=>$d['price'],'image'=>$d['imageUrl']??$d['image']??null,'is_available'=>$d['is_available']??$d['active']??true]);return response()->json(['data'=>$p->load('category')],201);}
 public function update(Request $r,int $id){$p=Product::where('restaurant_id',$r->user()->restaurant_id)->findOrFail($id);$d=$r->validate(['name'=>'sometimes|string|max:255','price'=>'sometimes|numeric|min:0','category_id'=>'nullable|integer','category'=>'nullable|string|max:100','imageUrl'=>'nullable|string|max:2048','image'=>'nullable|string|max:2048','active'=>'nullable|boolean','is_available'=>'nullable|boolean']);$categoryId=$d['category_id']??$p->category_id;if(!$categoryId&&isset($d['category'])){$c=Category::firstOrCreate(['restaurant_id'=>$r->user()->restaurant_id,'name'=>$d['category']],['display_order'=>0]);$categoryId=$c->id;}$p->update(['name'=>$d['name']??$p->name,'price'=>$d['price']??$p->price,'category_id'=>$categoryId,'image'=>$d['imageUrl']??$d['image']??$p->image,'is_available'=>$d['is_available']??$d['active']??$p->is_available]);return response()->json(['data'=>$p->load('category')]);}
 public function destroy(Request $r,int $id){Product::where('restaurant_id',$r->user()->restaurant_id)->findOrFail($id)->delete();return response()->noContent();}
 public function publicMenu(string $code){$t=Table::where('code',$code)->where('is_active',true)->firstOrFail();$items=Product::with('category')->where('restaurant_id',$t->restaurant_id)->where('is_available',true)->orderBy('category_id')->orderBy('name')->get();return response()->json(['data'=>['table'=>$t,'items'=>$items]]);}
}
