import { useEffect, useMemo, useState } from 'react';
import { Check, Image, Lock, Palette, RotateCcw, Upload, Wand2 } from 'lucide-react';
import { getBranding, resetBranding, saveBranding } from '../../api/branding';
import { useAuth } from '../../context/AuthContext';

const defaults={primary_color:'#B8793E',secondary_color:'#5B7A52',text_color:'#171717',button_color:'#171717',card_style:'rounded',font_family:'system',show_menupilot_branding:true};

export default function BrandingCustomization(){
 const {user}=useAuth(); const trial=user?.plan==='trial'&&user?.trial_ends_at&&new Date(user.trial_ends_at)>new Date();
 const paid=['pro','premium'].includes(user?.plan); const fullAccess=trial||paid; const premium=trial||user?.plan==='premium';
 const [settings,setSettings]=useState(defaults),[logo,setLogo]=useState(null),[background,setBackground]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{getBranding().then(x=>setSettings({...defaults,...(x||{})})).catch(()=>{}).finally(()=>setLoading(false));},[]);
 const previewStyle=useMemo(()=>({backgroundColor:settings.primary_color,color:settings.text_color}),[settings]);
 async function save(){setSaving(true);setMessage('');try{const updated=await saveBranding({...settings,logo,background,show_menupilot_branding:premium?settings.show_menupilot_branding:true});setSettings({...defaults,...updated});setLogo(null);setBackground(null);setMessage('تم حفظ هوية المنيو بنجاح.');}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 async function reset(){setSaving(true);try{const updated=await resetBranding();setSettings({...defaults,...updated});setMessage('تمت استعادة التصميم الافتراضي.')}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 if(loading)return <div className="p-8 text-center">جارِ تحميل إعدادات الهوية…</div>;
 return <div dir="rtl" className="space-y-7">
  <header><div className="flex items-center gap-2 text-copper"><Palette size={18}/><span className="text-sm font-black">هوية المطعم</span></div><h1 className="mt-2 text-3xl font-black">تخصيص المنيو</h1><p className="mt-2 text-sm leading-7 text-ink-soft/60">غيّر مظهر منيو QR ليحمل هوية مطعمك مع معاينة مباشرة.</p></header>
  {trial&&<div className="rounded-3xl border border-copper/25 bg-copper/10 p-5"><b>تجربتك المجانية تمنحك كل الميزات لمدة 14 يومًا.</b><p className="mt-1 text-sm text-ink-soft/70">جرّب الشعار والخلفية والألوان والخطوط وإزالة Branding الخاص بـ menuPilot.</p></div>}
  {!fullAccess&&<div className="flex items-center gap-3 rounded-3xl border border-dashed border-ink/15 bg-paper p-6"><Lock className="text-copper"/><div><b>تخصيص المنيو متاح من Pro</b><p className="mt-1 text-sm text-ink-soft/60">يمكنك معاينة المنيو، لكن حفظ الهوية يحتاج تجربة نشطة أو اشتراكًا مدفوعًا.</p></div></div>}
  <div className="grid gap-6 lg:grid-cols-[1fr_360px]">
   <section className="space-y-5 rounded-3xl border border-ink/8 bg-paper p-6">
    <div><h2 className="font-black">الشعار والصور</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">
     <label className="rounded-2xl border border-dashed border-ink/15 p-5 cursor-pointer"><Upload size={20} className="text-copper"/><b className="mt-2 block text-sm">شعار المطعم</b><span className="text-xs text-ink-soft/55">PNG / JPG / WEBP · 2MB</span><input disabled={!fullAccess} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>setLogo(e.target.files?.[0]||null)}/>{logo&&<p className="mt-2 text-xs text-herb">{logo.name}</p>}</label>
     <label className={`rounded-2xl border border-dashed border-ink/15 p-5 ${fullAccess?'cursor-pointer':'opacity-50'}`}><Image size={20} className="text-copper"/><b className="mt-2 block text-sm">خلفية المنيو</b><span className="text-xs text-ink-soft/55">Pro / Trial · حتى 5MB</span><input disabled={!fullAccess} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>setBackground(e.target.files?.[0]||null)}/>{background&&<p className="mt-2 text-xs text-herb">{background.name}</p>}</label>
    </div></div>
    <div><h2 className="font-black">الألوان</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{[['primary_color','اللون الأساسي'],['secondary_color','اللون الثانوي'],['text_color','لون النص'],['button_color','لون الأزرار']].map(([key,label])=><label key={key} className="text-sm font-bold">{label}<div className="mt-2 flex items-center gap-3 rounded-2xl border border-ink/10 p-2"><input disabled={!fullAccess} type="color" value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})} className="h-10 w-12"/><code className="text-xs">{settings[key]}</code></div></label>)}</div></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">شكل البطاقات<select disabled={!fullAccess} value={settings.card_style} onChange={e=>setSettings({...settings,card_style:e.target.value})} className="mt-2 w-full rounded-xl border border-ink/10 bg-paper-2 p-3"><option value="rounded">مستديرة</option><option value="soft">ناعمة</option><option value="square">مربعة</option></select></label><label className="text-sm font-bold">الخط{premium?<select value={settings.font_family} onChange={e=>setSettings({...settings,font_family:e.target.value})} className="mt-2 w-full rounded-xl border border-ink/10 bg-paper-2 p-3"><option value="system">System</option><option value="Cairo">Cairo</option><option value="Tajawal">Tajawal</option></select>:<div className="mt-2 flex items-center gap-2 rounded-xl border border-dashed p-3 text-xs text-ink-soft/55"><Lock size={14}/> Premium</div>}</label></div>
    <label className={`flex items-center justify-between rounded-2xl border p-4 ${premium?'':'opacity-60'}`}><span><b className="text-sm">إظهار Branding الخاص بـ menuPilot</b><span className="block text-xs text-ink-soft/55">يمكن إزالته في Premium أو أثناء Trial.</span></span><input disabled={!premium} type="checkbox" checked={premium?settings.show_menupilot_branding:false} onChange={e=>setSettings({...settings,show_menupilot_branding:e.target.checked})}/></label>
    <div className="flex flex-wrap gap-3"><button disabled={!fullAccess||saving} onClick={save} className="flex items-center gap-2 rounded-xl bg-copper px-5 py-3 text-sm font-black text-ink disabled:opacity-50"><Wand2 size={16}/>{saving?'جارٍ الحفظ…':'حفظ وتطبيق'}</button><button disabled={saving} onClick={reset} className="flex items-center gap-2 rounded-xl border border-ink/10 px-5 py-3 text-sm font-bold"><RotateCcw size={16}/>استعادة الافتراضي</button></div>
    {message&&<p className="text-sm font-bold text-herb">{message}</p>}
   </section>
   <aside className="lg:sticky lg:top-6 lg:self-start"><div className="overflow-hidden rounded-[32px] border border-ink/10 bg-paper shadow-xl"><div className="relative h-64 overflow-hidden" style={{backgroundImage:settings.background_url?`url(${settings.background_url})`:undefined,backgroundSize:'cover',backgroundPosition:'center',...(!settings.background_url?{backgroundColor:settings.primary_color}: {})}}><div className="absolute inset-0 bg-black/20"/><div className="relative z-10 flex h-full flex-col justify-end p-6 text-white"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white/90 text-ink overflow-hidden">{settings.logo_url?<img src={settings.logo_url} className="h-full w-full object-cover"/>:<Palette size={24}/>}</div><h3 className="mt-4 text-2xl font-black">معاينة المنيو</h3></div></div><div className="p-5"><div className="flex gap-2"><span className="h-9 flex-1 rounded-xl" style={{background:settings.primary_color}}/><span className="h-9 flex-1 rounded-xl" style={{background:settings.secondary_color}}/></div><div className="mt-4 rounded-2xl border border-ink/10 p-4" style={{borderRadius:settings.card_style==='square'?'8px':settings.card_style==='soft'?'20px':'28px'}}><b>برجر كلاسيك</b><p className="mt-1 text-xs opacity-60">لحم مشوي، جبنة، خس وصوص خاص</p><button className="mt-4 w-full rounded-xl px-4 py-2.5 text-sm font-black" style={{background:settings.button_color,color:'#fff'}}>إضافة للطلب</button></div>{!settings.show_menupilot_branding&&<p className="mt-4 text-center text-[11px] opacity-50">بدون Branding</p>}</div></div></aside>
  </div>
 </div>
}
