import React, { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Bell, Building2, CalendarPlus, ChevronDown, FileText, LayoutDashboard, Menu, Search, Settings, Store, Users, X } from "lucide-react";
import { api } from "../../api/client";
import AdminPageShell from "../../components/layout/AdminPageShell";
import AddonToggles from "../../components/subscription/AddonToggles";
import { PLAN_ORDER } from "../../config/subscriptions";

const planLabels = { basic: "Basic", pro: "Pro", trial: "Trial" };
const planOptions = PLAN_ORDER;
function formatDate(value) { if (!value) return "غير محدد"; return new Intl.DateTimeFormat("ar", { year: "numeric", month: "short", day: "numeric" }).format(new Date(value)); }
function StatCard({ title, value, icon: Icon, color, note }) { return <div className="admin-stat-card"><div className={`admin-stat-icon ${color}`}><Icon size={22} /></div><div><p>{title}</p><strong>{value}</strong><small>{note}</small></div></div>; }

export default function AdminDashboard() {
  const [restaurants, setRestaurants] = useState([]), [search, setSearch] = useState(""), [loading, setLoading] = useState(true), [savingId, setSavingId] = useState(null), [message, setMessage] = useState(""), [trialModal, setTrialModal] = useState(null), [trialDays, setTrialDays] = useState(14);
  async function loadRestaurants() { setLoading(true); try { const data = await api.get("/admin/restaurants"); setRestaurants(Array.isArray(data) ? data : []); } catch (error) { setMessage(error.message || "تعذر تحميل بيانات المطاعم"); } finally { setLoading(false); } }
  useEffect(() => { loadRestaurants(); }, []);
  const filteredRestaurants = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return restaurants; return restaurants.filter((r) => `${r.restaurant_name || ""} ${r.email || ""} ${r.plan || ""}`.toLowerCase().includes(query)); }, [restaurants, search]);
  const activeRestaurants = restaurants.filter((r) => r.plan === "trial" || PLAN_ORDER.includes(r.plan)).length;
  const trialRestaurants = restaurants.filter((r) => r.plan === "trial").length;
  const deliveryRestaurants = restaurants.filter((r) => PLAN_ORDER.includes(r.plan) && (r.addons || []).includes("delivery")).length;
  const paidRestaurants = restaurants.filter((r) => PLAN_ORDER.includes(r.plan)).length;
  async function changePlan(id, plan, addons) { setSavingId(id); setMessage(""); try { const data = await api.patch(`/admin/restaurants/${id}/plan`, addons ? { plan, addons } : { plan }); setRestaurants((current) => current.map((r) => r.id === id ? { ...r, ...data } : r)); setMessage("تم تحديث الباقة بنجاح."); } catch (error) { setMessage(error.message || "تعذر تحديث الباقة"); } finally { setSavingId(null); } }
  async function extendTrial() { if (!trialModal) return; setSavingId(trialModal.id); setMessage(""); try { const data = await api.post(`/admin/restaurants/${trialModal.id}/trial/extend`, { days: Number(trialDays) }); setRestaurants((current) => current.map((r) => r.id === trialModal.id ? { ...r, ...data } : r)); setTrialModal(null); setMessage(`تم تمديد التجربة ${trialDays} يومًا.`); } catch (error) { setMessage(error.message || "تعذر تمديد التجربة"); } finally { setSavingId(null); } }
  return <AdminPageShell>
      <section className="admin-heading"><div><p className="admin-overline"><Activity size={14} /> بيانات حقيقية من النظام</p><h1>لوحة تحكم المسؤول العام</h1><p>إدارة المطاعم والاشتراكات والتجارب مباشرة من قاعدة البيانات.</p></div><button className="admin-primary-button" onClick={loadRestaurants} disabled={loading}>{loading ? "جارٍ التحديث…" : "تحديث البيانات"}</button></section>
        <section className="admin-stats-grid"><StatCard title="إجمالي المطاعم" value={restaurants.length} icon={Building2} color="orange" note="من قاعدة البيانات" /><StatCard title="الحسابات النشطة" value={activeRestaurants} icon={Store} color="blue" note={`${paidRestaurants} باقات مدفوعة`} /><StatCard title="التجارب المجانية" value={trialRestaurants} icon={CalendarPlus} color="green" note="تحتاج متابعة" /><StatCard title="إضافة التوصيل" value={deliveryRestaurants} icon={Users} color="purple" note="مطاعم تستقبل طلبات أونلاين" /></section>
        <section className="admin-table-card"><div className="admin-table-heading"><div><p>إدارة الحسابات</p><h2>المطاعم المسجلة فعليًا</h2></div><span className="admin-live"><i /> متصل بالباكند</span></div><div className="admin-toolbar"><div className="admin-search"><Search size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث باسم المطعم أو البريد..." />{search && <button onClick={() => setSearch("")} aria-label="مسح البحث"><X size={15} /></button>}</div><span>عرض {filteredRestaurants.length} من {restaurants.length} مطاعم</span></div>{message && <div style={{ margin: "0 24px 14px", padding: "10px 12px", borderRadius: 8, background: "#f1fbf4", color: "#3e9b75", fontSize: 11, fontWeight: 700 }}>{message}</div>}<div className="admin-table-wrapper"><table className="admin-table"><thead><tr><th>اسم المطعم</th><th>البريد الإلكتروني</th><th>الباقة</th><th>الإضافات</th><th>حالة الحساب</th><th>انتهاء التجربة</th><th>تاريخ الاشتراك</th><th>الإجراءات</th></tr></thead><tbody>{filteredRestaurants.map((restaurant) => { const trial = restaurant.plan === "trial"; const active = trial || PLAN_ORDER.includes(restaurant.plan); return <tr key={restaurant.id}><td><strong>{restaurant.restaurant_name || "بدون اسم"}</strong></td><td>{restaurant.email}</td><td><select value={restaurant.plan} disabled={savingId === restaurant.id || trial} onChange={(e) => changePlan(restaurant.id, e.target.value)} style={{ border: 0, borderRadius: 6, padding: "5px 7px", color: "#6571a4", background: "#f0f1ff", fontSize: 9, fontWeight: 700 }}><option value="trial">Trial</option>{planOptions.map((plan) => <option key={plan} value={plan}>{planLabels[plan]}</option>)}</select></td><td><AddonToggles row={restaurant} disabled={savingId === restaurant.id} onChange={(addons) => changePlan(restaurant.id, restaurant.plan, addons)} /></td><td><span className={`admin-status ${active ? "active" : "inactive"}`}><i /> {active ? "نشط" : "غير نشط"}</span></td><td>{trial ? formatDate(restaurant.trial_ends_at) : "—"}</td><td>{formatDate(restaurant.subscription_started_at)}</td><td><div className="admin-actions">{trial && <button className="admin-edit" disabled={savingId === restaurant.id} onClick={() => { setTrialDays(14); setTrialModal(restaurant); }}><CalendarPlus size={14} /> تمديد</button>}{!trial && "—"}</div></td></tr>; })}</tbody></table>{!loading && filteredRestaurants.length === 0 && <div className="admin-empty">لا توجد مطاعم مطابقة للبحث</div>}{loading && <div className="admin-empty">جارٍ تحميل بيانات المطاعم...</div>}</div></section>
      {trialModal && <div className="admin-modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && setTrialModal(null)}><div className="admin-modal"><div className="admin-modal-header"><div><small>إدارة التجربة</small><h2>تمديد تجربة {trialModal.restaurant_name || "المطعم"}</h2></div><button onClick={() => setTrialModal(null)} aria-label="إغلاق"><X size={19} /></button></div><div className="admin-modal form" style={{ padding: "20px 24px 24px" }}><label>عدد الأيام<input type="number" min="1" max="365" value={trialDays} onChange={(e) => setTrialDays(e.target.value)} /></label><div className="admin-modal-actions"><button type="button" onClick={() => setTrialModal(null)}>إلغاء</button><button type="button" onClick={extendTrial}>تأكيد التمديد</button></div></div></div></div>}
  </AdminPageShell>;
}
