import { useEffect, useMemo, useState } from 'react';
import { Building2, Search, RefreshCw, Clock, CheckCircle2, Ban } from 'lucide-react';
import { getAllRestaurants, overrideRestaurantPlan, extendRestaurantTrial } from '../../api/admin';

const plans=['basic','pro','premium']; const labels={basic:'Basic',pro:'Pro',premium:'Premium',trial:'Trial'};
export default function RestaurantsManagement(){
 const [restaurants,setRestaurants]=useState([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null);
 async function load(){setLoading(true);setError('');try{setRestaurants(await getAllRestaurants()||[])}catch(e){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>restaurants.filter(r=>`${r.restaurant_name||''} ${r.email||''}`.toLowerCase().includes(search.toLowerCase())),[restaurants,search]);
 async function plan(id,value){setBusy(`${id}:plan`);try{const u=await overrideRestaurantPlan(id,value);setRestaurants(xs=>xs.map(x=>x.id===id?{...x,...u}:x))}catch(e){setError(e.message)}finally{setBusy(null)}}
 async function trial(id){const raw=window.prompt('عدد أيام التمديد؟','7');const days=Number(raw);if(!days)return;setBusy(`${id}:trial`);try{const u=await extendRestaurantTrial(id,days);setRestaurants(xs=>xs.map(x=>x.id===id?{...x,...u}:x))}catch(e){setError(e.message)}finally{setBusy(null)}}
 const status=r=>r.plan==='trial'?(r.trial_ends_at&&new Date(r.trial_ends_at)>new Date()?'تجربة نشطة':'منتهية'):(r.subscription_ends_at&&new Date(r.subscription_ends_at)<=new Date()?'منتهية':'نشط');
 return <div dir="rtl" className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-copper">Subscription Management</p><h1 className="mt-1 text-3xl font-black">إدارة الاشتراكات</h1><p className="mt-2 text-sm text-ink-soft/60">الخطة، Trial، وتواريخ انتهاء كل مطعم.</p></div><button onClick={load} disabled={loading} className="flex items-center gap-2 rounded-xl border border-ink/10 px-4 py-3 text-sm font-bold"><RefreshCw size={16} className={loading?'animate-spin':''}/>تحديث</button></div>{error&&<div className="rounded-2xl bg-brick/10 p-4 text-sm font-bold text-brick">{error}</div>}<div className="rounded-2xl border border-ink/10 bg-paper p-4"><div className="relative max-w-md"><Search className="absolute right-3 top-3 text-ink-soft/40" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن مطعم أو بريد إلكتروني…" className="w-full rounded-xl border border-ink/10 bg-paper-2 py-3 pr-10 pl-4 outline-none focus:border-copper"/></div></div>{loading?<div className="rounded-3xl bg-paper p-10 text-center">جارِ تحميل المطاعم…</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=>{const s=status(r);const days=r.plan==='trial'&&r.trial_ends_at?Math.max(0,Math.ceil((new Date(r.trial_ends_at)-Date.now())/86400000)):null;return <article key={r.id} className="rounded-3xl border border-ink/10 bg-paper p-5 shadow-sm"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl bg-copper/10 text-copper"><Building2 size={23}/></div><span className={`flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${s==='نشط'||s==='تجربة نشطة'?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>{s==='نشط'||s==='تجربة نشطة'?<CheckCircle2 size={13}/>:<Ban size={13}/>} {s}</span></div><h2 className="mt-5 text-xl font-black">{r.restaurant_name||'بدون اسم'}</h2><p className="mt-2 truncate text-sm text-ink-soft/60">{r.email}</p><div className="mt-5 flex items-center justify-between"><span className="rounded-lg bg-ink/5 px-3 py-1 text-xs font-black">{labels[r.plan]||r.plan}</span>{r.plan==='trial'&&days!==null&&<span className="flex items-center gap-1 text-xs font-bold text-copper"><Clock size={13}/>{days} يوم</span>}</div><div className="mt-4 grid grid-cols-3 gap-2">{plans.map(p=><button key={p} disabled={busy!==null} onClick={()=>plan(r.id,p)} className={`rounded-xl border px-2 py-2 text-xs font-bold ${r.plan===p?'border-copper bg-copper/10':'border-ink/10'}`}>{labels[p]}</button>)}<button disabled={busy!==null} onClick={()=>trial(r.id)} className="rounded-xl bg-ink px-2 py-2 text-xs font-bold text-paper">+ Trial</button></div></article>})}</div>}</div>;
}
