import { useMemo, useState } from "react";
import { Building2, Pencil, Plus, Search, Trash2, X } from "lucide-react";

const initialRestaurants = [
  { id: 1, name: "مطعم الذوق", city: "غزة", phone: "+970 599 123 456", status: "نشط", ownerId: 1, plan: "Premium" },
  { id: 2, name: "Burger House", city: "رام الله", phone: "+970 599 456 789", status: "نشط", ownerId: 2, plan: "Pro" },
  { id: 3, name: "Italian Corner", city: "نابلس", phone: "+970 599 987 654", status: "موقوف", ownerId: 3, plan: "Basic" },
];

export default function RestaurantsManagement() {
  const [restaurants, setRestaurants] = useState(initialRestaurants);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: "", city: "", phone: "", ownerId: "", plan: "Pro", status: "نشط" });
  const filtered = useMemo(() => restaurants.filter(r => `${r.name} ${r.city}`.toLowerCase().includes(search.toLowerCase())), [restaurants, search]);
  const openCreate = () => { setEditing("new"); setForm({ name: "", city: "", phone: "", ownerId: "", plan: "Pro", status: "نشط" }); };
  const openEdit = (restaurant) => { setEditing(restaurant.id); setForm({ ...restaurant, ownerId: String(restaurant.ownerId) }); };
  const save = (e) => { e.preventDefault(); if (!form.name.trim()) return; if (editing === "new") setRestaurants(prev => [...prev, { ...form, id: Date.now(), ownerId: Number(form.ownerId) || null }]); else setRestaurants(prev => prev.map(r => r.id === editing ? { ...form, id: editing, ownerId: Number(form.ownerId) || null } : r)); setEditing(null); };
  const remove = (id) => { if (window.confirm("هل تريد حذف هذا المطعم؟")) setRestaurants(prev => prev.filter(r => r.id !== id)); };
  return <div dir="rtl" className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-copper">إدارة المنصة</p><h1 className="mt-1 text-3xl font-black">إدارة المطاعم</h1><p className="mt-2 text-sm text-ink-soft/60">أضف المطاعم وعدّل بياناتها وأدر حالتها.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-copper px-5 py-3 text-sm font-black text-ink"><Plus size={18}/>إضافة مطعم</button></div>
    <div className="rounded-2xl border border-ink/10 bg-paper p-4"><div className="relative max-w-md"><Search className="absolute right-3 top-3 text-ink-soft/40" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن مطعم أو مدينة..." className="w-full rounded-xl border border-ink/10 bg-paper-2 py-3 pr-10 pl-4 outline-none focus:border-copper"/></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><article key={r.id} className="rounded-2xl border border-ink/10 bg-paper p-5 shadow-sm"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl bg-copper/10 text-copper"><Building2 size={23}/></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${r.status === "نشط" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`}>{r.status}</span></div><h2 className="mt-5 text-xl font-black">{r.name}</h2><p className="mt-2 text-sm text-ink-soft/60">{r.city} · {r.phone}</p><div className="mt-5 flex items-center justify-between border-t border-ink/10 pt-4"><span className="rounded-lg bg-ink/5 px-3 py-1 text-xs font-bold">{r.plan}</span><div className="flex gap-2"><button onClick={()=>openEdit(r)} className="rounded-lg p-2 text-copper hover:bg-copper/10"><Pencil size={18}/></button><button onClick={()=>remove(r.id)} className="rounded-lg p-2 text-brick hover:bg-brick/10"><Trash2 size={18}/></button></div></div></article>)}</div>
    {editing && <div className="fixed inset-0 z-[60] grid place-items-center bg-ink/60 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-paper p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{editing === "new" ? "إضافة مطعم جديد" : "تعديل بيانات المطعم"}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["name","اسم المطعم"],["city","المدينة"],["phone","رقم الهاتف"],["ownerId","معرّف المالك"]].map(([key,label])=><label key={key} className="text-sm font-bold">{label}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-ink/10 bg-paper-2 px-4 py-3 outline-none focus:border-copper"/></label>)}<label className="text-sm font-bold">الباقة<select value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})} className="mt-2 w-full rounded-xl border border-ink/10 bg-paper-2 px-4 py-3"><option>Basic</option><option>Pro</option><option>Premium</option></select></label><label className="text-sm font-bold">الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 w-full rounded-xl border border-ink/10 bg-paper-2 px-4 py-3"><option>نشط</option><option>موقوف</option></select></label></div><div className="mt-6 flex gap-3"><button className="flex-1 rounded-xl bg-copper py-3 font-black text-ink">حفظ البيانات</button><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border border-ink/10 px-5">إلغاء</button></div></form></div>}
  </div>;
}
